# Премиальные бренды на главной: (отображаемое имя, slug для ?brand=… в каталоге)
FEATURED_HOME_BRANDS = [
    ("Amouage", "amouage"),
    ("Byredo", "byredo"),
    ("Diptyque", "diptyque"),
    ("Le Labo", "le-labo"),
    ("Creed", "creed"),
    ("Tom Ford", "tom-ford"),
    ("Xerjoff", "xerjoff"),
    ("Chanel", "chanel"),
    ("Kilian", "kilian"),
    ("Frédéric Malle", "frederic-malle"),
    ("Parfums de Marly", "parfums-de-marly"),
    ("Dior", "dior"),
    ("Mancera", "mancera"),
    ("Montale", "montale"),
    ("Nishane", "nishane"),
    ("Guerlain", "guerlain"),
]

# Мега-меню в шапке: порядок колонок как в макете (слева направо, сверху вниз)
MEGA_MENU_BRANDS = [
    ("Amouage", "amouage"),
    ("Attar Collection", "attar-collection"),
    ("Burberry", "burberry"),
    ("Byredo", "byredo"),
    ("Bvlgari", "bvlgari"),
    ("Chanel", "chanel"),
    ("Creed", "creed"),
    ("Dior", "dior"),
    ("Carolina Herrera", "carolina-herrera"),
    ("Ex Nihilo", "ex-nihilo"),
    ("Escentric Molecules", "escentric-molecules"),
    ("Gucci", "gucci"),
    ("Givenchy", "givenchy"),
    ("Giorgio Armani", "giorgio-armani"),
    ("Giardini di Toscana", "giardini-di-toscana"),
    ("Hugo Boss", "hugo-boss"),
    ("Hermes", "hermes"),
    ("Hormone Paris", "hormone-paris"),
    ("Jo Malone", "jo-malone"),
    ("Jean Paul Gaultier", "jean-paul-gaultier"),
    ("Kajal", "kajal"),
    ("Kilian", "kilian"),
    ("Maison Francis Kurkdjian", "maison-francis-kurkdjian"),
    ("Marc-Antoine Barrois", "marc-antoine-barrois"),
    ("Marc Jacobs", "marc-jacobs"),
    ("Nasomatto", "nasomatto"),
    ("Nishane", "nishane"),
    ("Narciso Rodriguez", "narciso-rodriguez"),
    ("Orto Parisi", "orto-parisi"),
    ("Parfums de Marly", "parfums-de-marly"),
    ("Paco Rabanne", "paco-rabanne"),
    ("Roja", "roja"),
    ("Sospiro Perfumes", "sospiro-perfumes"),
    ("Versace", "versace"),
    ("Xerjoff", "xerjoff"),
    ("Yves Saint Laurent", "yves-saint-laurent"),
    ("Zarkoperfume", "zarkoperfume"),
    ("Zadig & Voltaire", "zadig-voltaire"),
    ("Zoologist", "zoologist"),
    ("Zielinski & Rozen", "zielinski-rozen"),
    ("Emporio Armani", "emporio-armani"),
    ("Clive Christian", "clive-christian"),
    ("Essential Parfums", "essential-parfums"),
    ("Vilhelm Parfumerie", "vilhelm-parfumerie"),
]
