# Generated by Django 4.2.30 on 2026-06-02 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('legal_name', models.CharField(blank=True, max_length=255)),
                ('inn', models.CharField(blank=True, max_length=12, verbose_name='ИНН')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('type', models.CharField(choices=[('INDIVIDUAL', 'Физ. лицо'), ('COMPANY', 'Компания')], default='COMPANY', max_length=12)),
                ('address', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='core.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
