"""
Django settings for perfume_store project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging
import logging.handlers
import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Корневой `.env` (не коммитится) — подхватывается до чтения os.environ ниже.
load_dotenv(BASE_DIR / ".env")

# ЮKassa (тестовые ключи из личного кабинета: Настройки → API-ключи, режим «Тест»).
YOOKASSA_SHOP_ID = os.environ.get("YOOKASSA_SHOP_ID", "").strip()
YOOKASSA_SECRET_KEY = os.environ.get("YOOKASSA_SECRET_KEY", "").strip()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# На сервере задайте в .env: SECRET_KEY, DEBUG=False, ALLOWED_HOSTS, CSRF_TRUSTED_ORIGINS.
SECRET_KEY = os.environ.get(
    "SECRET_KEY",
    "django-insecure-7^(+ng0r29ylo51zy=tb49ek&*7@w4^8bqxghaf-!caj%5i!pp",
)

DEBUG = os.environ.get("DEBUG", "True").strip().lower() in ("1", "true", "yes")

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]

_csrf_origins = os.environ.get("CSRF_TRUSTED_ORIGINS", "").strip()
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(",") if o.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'products',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'perfume_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.cart_context',
                'core.context_processors.favorite_context',
                'core.context_processors.nav_mega_menu',
            ],
        },
    },
]

WSGI_APPLICATION = 'perfume_store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

# Логи в файл на сервере (ispmanager часто не показывает traceback в браузере).
# Включается при DEBUG=False или если в .env задано DJANGO_FILE_LOG=1.
_log_to_file = (not DEBUG) or os.environ.get("DJANGO_FILE_LOG", "").strip().lower() in (
    "1",
    "true",
    "yes",
)
if _log_to_file:
    _log_dir = BASE_DIR / "logs"
    _log_path = _log_dir / "django.log"
    try:
        _log_dir.mkdir(exist_ok=True)
    except OSError:
        _log_path = BASE_DIR / "django.log"
    _log_level_name = os.environ.get("DJANGO_LOG_LEVEL", "ERROR").strip().upper()
    _file_log_level = getattr(logging, _log_level_name, logging.ERROR)
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "%(levelname)s %(asctime)s %(name)s %(process)d: %(message)s",
            },
        },
        "handlers": {
            "file": {
                "level": _file_log_level,
                "class": "logging.handlers.RotatingFileHandler",
                "filename": str(_log_path),
                "maxBytes": 2 * 1024 * 1024,
                "backupCount": 5,
                "formatter": "verbose",
                "encoding": "utf-8",
            },
        },
        "loggers": {
            "django.request": {
                "handlers": ["file"],
                "level": _file_log_level,
                "propagate": False,
            },
            "django": {
                "handlers": ["file"],
                "level": _file_log_level,
                "propagate": False,
            },
        },
        "root": {
            "handlers": ["file"],
            "level": _file_log_level,
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
