"""
Django settings for perfume_store project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import logging
import logging.handlers
import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Корневой `.env` (не коммитится) — подхватывается до чтения os.environ ниже.
load_dotenv(BASE_DIR / ".env")

# ЮKassa (тестовые ключи из личного кабинета: Настройки → API-ключи, режим «Тест»).
YOOKASSA_SHOP_ID = os.environ.get("YOOKASSA_SHOP_ID", "").strip()
YOOKASSA_SECRET_KEY = os.environ.get("YOOKASSA_SECRET_KEY", "").strip()

# Секрет для выгрузки заказов в учётную систему (заголовок X-Accounting-Token).
ACCOUNTING_SYNC_TOKEN = os.environ.get("ACCOUNTING_SYNC_TOKEN", "").strip()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# На сервере задайте в .env: SECRET_KEY, DEBUG=False, ALLOWED_HOSTS, CSRF_TRUSTED_ORIGINS.
_INSECURE_DEV_SECRET_KEY = (
    "django-insecure-7^(+ng0r29ylo51zy=tb49ek&*7@w4^8bqxghaf-!caj%5i!pp"
)

DEBUG = os.environ.get("DEBUG", "True").strip().lower() in ("1", "true", "yes")

_secret_from_env = os.environ.get("SECRET_KEY", "").strip()
if _secret_from_env:
    SECRET_KEY = _secret_from_env
elif DEBUG:
    # Только для локальной разработки; в production DEBUG=False и SECRET_KEY обязателен.
    SECRET_KEY = _INSECURE_DEV_SECRET_KEY
else:
    raise ImproperlyConfigured(
        "SECRET_KEY must be set via environment variable when DEBUG=False."
    )

if not DEBUG and SECRET_KEY == _INSECURE_DEV_SECRET_KEY:
    raise ImproperlyConfigured(
        "SECRET_KEY must not use the insecure development default in production."
    )

ALLOWED_HOSTS = [
    h.strip()
    for h in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if h.strip()
]

_csrf_origins = os.environ.get("CSRF_TRUSTED_ORIGINS", "").strip()
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(",") if o.strip()]

# Покупка подарочных карт через API без оплаты — только явно в dev/тесте.
GIFT_CARD_PURCHASE_ENABLED = os.environ.get(
    "GIFT_CARD_PURCHASE_ENABLED",
    "True" if DEBUG else "False",
).strip().lower() in ("1", "true", "yes")

# Опциональный allowlist IP для webhook ЮKassa (через запятую). Пусто = проверка отключена.
_yookassa_ips = os.environ.get("YOOKASSA_WEBHOOK_IPS", "").strip()
YOOKASSA_WEBHOOK_IPS = frozenset(
    ip.strip() for ip in _yookassa_ips.split(",") if ip.strip()
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'products',
    'api',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'perfume_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.cart_context',
                'core.context_processors.favorite_context',
                'core.context_processors.nav_mega_menu',
            ],
        },
    },
]

WSGI_APPLICATION = 'perfume_store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': os.environ.get("DB_ENGINE", "django.db.backends.sqlite3"),
        'NAME': os.environ.get("DB_NAME", BASE_DIR / "db.sqlite3"),
        'USER': os.environ.get("DB_USER", ""),
        'PASSWORD': os.environ.get("DB_PASSWORD", ""),
        'HOST': os.environ.get("DB_HOST", ""),
        'PORT': os.environ.get("DB_PORT", ""),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.yandex.ru"          # или smtp.yandex.ru, smtp.mail.ru и т.д.
EMAIL_PORT = 587
EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", f"Accord <{EMAIL_HOST_USER}>")

YANDEX_CAPTCHA_CLIENT_KEY = os.getenv("YANDEX_CAPTCHA_CLIENT_KEY", "")
YANDEX_CAPTCHA_SERVER_KEY = os.getenv("YANDEX_CAPTCHA_SERVER_KEY", "")

# Логи в файл на сервере (ispmanager часто не показывает traceback в браузере).
# Включается при DEBUG=False или если в .env задано DJANGO_FILE_LOG=1.
_log_to_file = (not DEBUG) or os.environ.get("DJANGO_FILE_LOG", "").strip().lower() in (
    "1",
    "true",
    "yes",
)
if _log_to_file:
    _log_dir = BASE_DIR / "logs"
    _log_path = _log_dir / "django.log"
    try:
        _log_dir.mkdir(exist_ok=True)
    except OSError:
        _log_path = BASE_DIR / "django.log"
    _log_level_name = os.environ.get("DJANGO_LOG_LEVEL", "ERROR").strip().upper()
    _file_log_level = getattr(logging, _log_level_name, logging.ERROR)
    LOGGING = {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": {
            "verbose": {
                "format": "%(levelname)s %(asctime)s %(name)s %(process)d: %(message)s",
            },
        },
        "handlers": {
            "file": {
                "level": _file_log_level,
                "class": "logging.handlers.RotatingFileHandler",
                "filename": str(_log_path),
                "maxBytes": 2 * 1024 * 1024,
                "backupCount": 5,
                "formatter": "verbose",
                "encoding": "utf-8",
            },
        },
        "loggers": {
            "django.request": {
                "handlers": ["file"],
                "level": _file_log_level,
                "propagate": False,
            },
            "django": {
                "handlers": ["file"],
                "level": _file_log_level,
                "propagate": False,
            },
        },
        "root": {
            "handlers": ["file"],
            "level": _file_log_level,
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# --- Production security (Django deployment checklist) ---
def _env_bool(name: str, default: str) -> bool:
    return os.environ.get(name, default).strip().lower() in ("1", "true", "yes")


if not DEBUG:
    # За reverse-proxy (nginx/ispmanager): Django видит HTTPS по заголовку.
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
    SECURE_SSL_REDIRECT = _env_bool("SECURE_SSL_REDIRECT", "True")
    SECURE_HSTS_SECONDS = int(os.environ.get("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _env_bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", "True")
    SECURE_HSTS_PRELOAD = _env_bool("SECURE_HSTS_PRELOAD", "True")
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"
    X_FRAME_OPTIONS = "DENY"

    if not ALLOWED_HOSTS or ALLOWED_HOSTS == ["localhost", "127.0.0.1"]:
        raise ImproperlyConfigured(
            "ALLOWED_HOSTS must be set to your domain(s) when DEBUG=False."
        )
    if not CSRF_TRUSTED_ORIGINS:
        raise ImproperlyConfigured(
            "CSRF_TRUSTED_ORIGINS must include https://your-domain when DEBUG=False."
        )
else:
    # Локально: без принудительного HTTPS, но базовые заголовки остаются.
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
