# Generated by Django 5.2.6 on 2026-05-01 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_giftcard_code_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='yookassa_payment_id',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Платёж ЮKassa'),
        ),
    ]
