# Generated by Django 5.2.6 on 2026-05-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_order_yookassa_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='brand',
            name='origin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='brand',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
